In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_excel(r'sqli.xlsx', engine='openpyxl')
df = df.fillna('')
df

Query Label Unnamed: 2  \
0      )  union select * from information_schema.tab...    MD              
1     1 union all select 1,2,3,4,5,6,name from sysob...    MD              
2                          union all select @@version--    MD              
3      union select * from users where login  =  cha...    MD              
4                                          union select    MD              
...                                                 ...   ...        ...   
1994   Their motto , large billboard stated &quot; W...    NV              
1995   In wanted point danger even bigger ruins Schw...    NV              
1996   Chatting many people passing &quot; construct...    NV              
1997   However , beginning resign town continues sta...    NV              
1998   We told public statements made Mayor also imp...    NV              

     Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  
0                                                            
1                                                            
2                                                            
3                                                            
4                                                            
...         ...        ...        ...        ...        ...  
1994                                                         
1995                                                         
1996                                                         
1997                                                         
1998                                                         

[1999 rows x 8 columns]

In [3]:
 from sklearn.feature_extraction.text import CountVectorizer
df_MD = [row['Query'] for index,row in df.iterrows() if row['Label'] == 'MD']
df_MD


[' )  union select * from information_schema.tables;',
 "1 union all select 1,2,3,4,5,6,name from sysobjects where xtype  =  'u' --",
 ' union all select @@version--',
 ' union select * from users where login  =  char ( 114,111,111,116 ) ;',
 ' union select',
 " union select 1,load_file ( '/etc/passwd' ) ,1,1,1;",
 ' union  ( select @@version )  --',
 ' union  ( select NULL,  ( select @@version  )  )   --',
 ' union  ( select NULL, NULL,  ( select @@version  )  )   --',
 ' union  ( select NULL, NULL, NULL,   ( select @@version  )  )   --',
 ' union  ( select NULL, NULL, NULL, NULL,   ( select @@version  )  )   --',
 ' union  ( select NULL, NULL, NULL, NULL,  NULL,  ( select @@version  )  )   --',
 ' 1 + ( \\ )  union select null,@@VERSION -- 1',
 ' 1.&&1 union select 1,version (  )  -- 1',
 ' 1.&&@ union select 1,version (  )  -- 1',
 ' 1 +  ( \\. )  union select null,@@VERSION -- 1',
 ' 1.  union select 1,version (  )  -- 1',
 ' 1. union select 1,banner from v$version where rownum = 1

In [4]:
vec = CountVectorizer()

In [5]:
l=vec.fit_transform(df_MD)
print(l.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]]


In [6]:
 print(vec.get_feature_names())

['11', '111', '114', '116', '1234', '1_', '1a', '81dc9bdb52d04dc20036dbd8313ed055', 'admin', 'all', 'and', 'banner', 'char', 'datadir', 'etc', 'from', 'information_schema', 'load_file', 'login', 'name', 'null', 'passwd', 'rownum', 'select', 'sysobjects', 'tables', 'union', 'users', 'version', 'where', 'x27union', 'xtype']


In [7]:
# print(l.toarray())
table_MD=pd.DataFrame(l.toarray(), columns=vec.get_feature_names())
table_MD

11  111  114  116  1234  1_  1a  81dc9bdb52d04dc20036dbd8313ed055  admin  \
0     0    0    0    0     0   0   0                                 0      0   
1     0    0    0    0     0   0   0                                 0      0   
2     0    0    0    0     0   0   0                                 0      0   
3     0    2    1    1     0   0   0                                 0      0   
4     0    0    0    0     0   0   0                                 0      0   
..   ..  ...  ...  ...   ...  ..  ..                               ...    ...   
450   0    0    0    0     0   0   0                                 0      0   
451   0    0    0    0     0   0   0                                 0      0   
452   0    0    0    0     0   0   0                                 0      0   
453   0    0    0    0     0   0   0                                 0      0   
454   0    0    0    0     0   0   0                                 0      0   

     all  ...  rownum  select  sysobjects  tables  union  users  version  \
0      0  ...       0       1           0       1      1      0        0   
1      1  ...       0       1           1       0      1      0        0   
2      1  ...       0       1           0       0      1      0        1   
3      0  ...       0       1           0       0      1      1        0   
4      0  ...       0       1           0       0      1      0        0   
..   ...  ...     ...     ...         ...     ...    ...    ...      ...   
450    0  ...       0       1           0       0      1      0        0   
451    0  ...       0       1           0       0      1      0        0   
452    0  ...       0       1           0       0      1      0        0   
453    0  ...       0       1           0       0      1      0        0   
454    1  ...       0       1           1       0      1      0        0   

     where  x27union  xtype  
0        0         0      0  
1        1         0      1  
2        0         0      0  
3        1         0      0  
4        0         0      0  
..     ...       ...    ...  
450      0         0      0  
451      0         0      0  
452      0         0      0  
453      0         0      0  
454      1         0      1  

[455 rows x 32 columns]

In [8]:
df_HG = [row['Query'] for index,row in df.iterrows() if row['Label'] == 'HG']
df_HG

["' OR 1=1 ;",
 "' OR 1=1 -- --",
 "' OR 1=1 -- #",
 "' OR 1=1 -- %",
 "' OR 1=1 -- '",
 "' OR 1=1 #",
 "' OR 1=2 ;",
 "' OR 1=2 -- --",
 "' OR 1=2 -- #",
 "' OR 1=2 -- %",
 "' OR 1=2 -- '",
 "' OR 1=2 #",
 "' OR 2=1 ;",
 "' OR 2=1 -- --",
 "' OR 2=1 -- #",
 "' OR 2=1 -- %",
 "' OR 2=1 -- '",
 "' OR 2=1 #",
 "' OR 2=2 ;",
 "' OR 2=2 -- --",
 "' OR 2=2 -- #",
 "' OR 2=2 -- %",
 "' OR 2=2 -- '",
 "' OR 2=2 #",
 "' OR a=a ;",
 "' OR a=a -- --",
 "' OR a=a -- #",
 "' OR a=a -- %",
 "' OR a=a -- '",
 "' OR a=a #",
 "') OR 1=1 ;",
 "') OR 1=1 -- --",
 "') OR 1=1 -- #",
 "') OR 1=1 -- %",
 "') OR 1=1 -- '",
 "') OR 1=1 #",
 "') OR 1=2 ;",
 "') OR 1=2 -- --",
 "') OR 1=2 -- #",
 "') OR 1=2 -- %",
 "') OR 1=2 -- '",
 ') OR 1=2 #',
 "') OR 2=1 ;",
 "') OR 2=1 -- --",
 "') OR 2=1 -- #",
 "') OR 2=1 -- %",
 "') OR 2=1 -- '",
 "') OR 2=1 #",
 "') OR 2=2 ;",
 "') OR 2=2 -- --",
 "'] OR a=a #",
 "'] OR a=a -- '",
 "'] OR a=a -- %",
 "'] OR a=a -- #",
 "'] OR a=a -- --",
 "'] OR a=a ;",
 "'] OR 2=2 #"

In [9]:
# vec = CountVectorizer()
arr2=vec.fit_transform(df_HG)


In [10]:
table_HG=pd.DataFrame(arr2.toarray(), columns=vec.get_feature_names())
table_HG


10  10000000  101  11  110  116  120  1234  172  23  ...  users  var  \
0     0         0    0   0    0    0    0     0    0   0  ...      0    0   
1     0         0    0   0    0    0    0     0    0   0  ...      0    0   
2     0         0    0   0    0    0    0     0    0   0  ...      0    0   
3     0         0    0   0    0    0    0     0    0   0  ...      0    0   
4     0         0    0   0    0    0    0     0    0   0  ...      0    0   
..   ..       ...  ...  ..  ...  ...  ...   ...  ...  ..  ...    ...  ...   
559   0         0    0   0    0    0    0     0    0   0  ...      0    0   
560   0         0    0   0    0    0    0     0    0   0  ...      0    0   
561   0         0    0   0    0    0    0     0    0   0  ...      0    0   
562   0         0    0   0    0    0    0     0    0   0  ...      0    1   
563   0         0    0   0    0    0    0     0    0   0  ...      0    0   

     version  where  xp  xp_  xp_cmdshell  xp_regread  xtype  ã½  
0          0      0   0    0            0           0      0   0  
1          0      0   0    0            0           0      0   0  
2          0      0   0    0            0           0      0   0  
3          0      0   0    0            0           0      0   0  
4          0      0   0    0            0           0      0   0  
..       ...    ...  ..  ...          ...         ...    ...  ..  
559        0      0   0    0            0           1      0   0  
560        0      0   0    0            0           0      0   0  
561        0      0   0    0            0           0      0   0  
562        0      0   0    0            0           0      0   0  
563        0      0   0    0            0           0      0   0  

[564 rows x 98 columns]

In [11]:
df_UK = [row['Query'] for index,row in df.iterrows() if row['Label'] == 'UK']
df_UK


['$',
 'www',
 'com',
 'get',
 '.',
 ')',
 '(',
 '~',
 'hi',
 'hello',
 'do',
 'can',
 'could',
 'have',
 'it',
 '≠',
 '`',
 '∈',
 '∉',
 '∅',
 '√',
 '≪',
 '∞',
 '∩',
 'π',
 'Kg',
 'g',
 'cm',
 'm',
 '÷',
 '°\u200eF',
 '°\u200eC',
 'log',
 'km/h',
 'loge x',
 'ln x',
 'x',
 '(a,b)',
 'sin',
 '90°',
 '105°',
 '75°',
 '120°',
 '60°',
 '135°',
 '0°',
 '180°',
 '16\xa02⁄3g',
 '2π',
 'x',
 'Cos',
 'xy',
 '→',
 '∫',
 '±',
 '∷',
 '∞',
 '∮',
 '∎',
 'sinh\xa02\xa0θ\xa0',
 ' (sinh θ)\xa0',
 'cos\xa0t\xa0',
 'sin\xa0t',
 'cosh(θ) ',
 'sinh(θ))  ',
 '(tanh(θ)',
 '☥',
 'a^b',
 '√a',
 '4√a',
 'n√a',
 '∠',
 '',
 '',
 '',
 '≅',
 '|x-y|',
 '≪',
 '( )',
 'x!',
 '(f\xa0∘\xa0g)',
 '∑',
 '∑∑',
 'e',
 'A⊗B',
 '|\xa0A\xa0|',
 'A†',
 'A\xa0-1',
 'rank(A)',
 'f\xa0(x)',
 'E(X | Y)',
 'var(X)',
 'σ2',
 'U(a,b)',
 'nPk',
 'nCk',
 '⇒',
 '∀',
 '∃',
 '∄',
 '∴',
 '∵',
 'ε',
 '∫∫',
 '∫∫∫',
 '∮',
 '∯',
 '∰',
 '',
 '',
 'δ',
 '∇',
 'δ',
 'I',
 'II',
 'IV',
 'V',
 'VI',
 'VII',
 'XI',
 'XXX',
 '',
 '',
 '',
 '',
 '',
 '⇔

In [12]:
vec3 = CountVectorizer()
arr3 = vec3.fit_transform(df_UK)
# vec3 = CountVectorizer()
# arr3=vec3.fit_transform()
table_UK=pd.DataFrame(arr3.toarray(), columns=vec3.get_feature_names())
table_UK
# print(arr3.toarray())
# print(vec3.get_feature_names())


105  120  135  16  180  2a  2π  3g  60  75  ...  tanh  var  vi  vii  www  \
0      0    0    0   0    0   0   0   0   0   0  ...     0    0   0    0    0   
1      0    0    0   0    0   0   0   0   0   0  ...     0    0   0    0    1   
2      0    0    0   0    0   0   0   0   0   0  ...     0    0   0    0    0   
3      0    0    0   0    0   0   0   0   0   0  ...     0    0   0    0    0   
4      0    0    0   0    0   0   0   0   0   0  ...     0    0   0    0    0   
..   ...  ...  ...  ..  ...  ..  ..  ..  ..  ..  ...   ...  ...  ..  ...  ...   
204    0    0    0   0    0   0   0   0   0   0  ...     0    0   0    0    0   
205    0    0    0   0    0   0   0   0   0   0  ...     0    0   0    0    0   
206    0    0    0   0    0   0   0   0   0   0  ...     0    0   0    0    0   
207    0    0    0   0    0   0   0   0   0   0  ...     0    0   0    0    0   
208    0    0    0   0    0   0   0   0   0   0  ...     0    0   0    0    0   

     xi  xxx  xy  σ2  σx  
0     0    0   0   0   0  
1     0    0   0   0   0  
2     0    0   0   0   0  
3     0    0   0   0   0  
4     0    0   0   0   0  
..   ..  ...  ..  ..  ..  
204   0    0   0   0   0  
205   0    0   0   0   0  
206   0    0   0   0   0  
207   0    0   0   0   0  
208   0    0   0   0   0  

[209 rows x 47 columns]

In [13]:
df_NV = [row['Query'] for index,row in df.iterrows() if row['Label'] == 'NV']
df_NV


[' Man star; soul Render honest perfect man, Commands light, influence, fate; Nothing falls early late',
 ' Our acts angels are, good ill, Our fatal shadows walk us still',
 ' Epilogue Beaumont Fletcher’s Honest Man’s Fortune Cast bantling rocks, Suckle she-wolf’s teat; Wintered hawk fox, Power speed hands feet',
 ' I read day verses written eminent painter original conventional',
 ' The soul always hears admonition lines, let subject may',
 ' The sentiment instil value thought may contain',
 ' To believe thought, believe true private heart true men, — genius',
 ' Speak latent conviction, shall universal sense; inmost due time becomes outmost, — first thought rendered back us trumpets Last Judgment',
 ' Familiar voice mind each, highest merit ascribe Moses, Plato, Milton is, set naught books traditions, spoke men thought',
 ' A man learn detect watch gleam light flashes across mind within, lustre firmament bards sages',
 ' Yet dismisses without notice thought, his',
 ' In every work ge

In [14]:
vec2= CountVectorizer()
# X_s = vec_s.fit_transform(stmt_docs)
arr4=vec2.fit_transform(df_NV)
table_NV=pd.DataFrame(arr4.toarray(), columns=vec2.get_feature_names())
table_NV

000  10  100  100aklima  116  12  125  13  138  14  ...  york  yorkshire  \
0      0   0    0          0    0   0    0   0    0   0  ...     0          0   
1      0   0    0          0    0   0    0   0    0   0  ...     0          0   
2      0   0    0          0    0   0    0   0    0   0  ...     0          0   
3      0   0    0          0    0   0    0   0    0   0  ...     0          0   
4      0   0    0          0    0   0    0   0    0   0  ...     0          0   
..   ...  ..  ...        ...  ...  ..  ...  ..  ...  ..  ...   ...        ...   
596    0   0    0          0    0   0    0   0    0   0  ...     0          0   
597    0   0    0          0    0   0    0   0    0   0  ...     0          0   
598    0   0    0          0    0   0    0   0    0   0  ...     0          0   
599    0   0    0          0    0   0    0   0    0   0  ...     0          0   
600    0   0    0          0    0   0    0   0    0   0  ...     0          0   

     you  young  your  yourself  youth  zhang  zigzag  zweig  
0      0      0     0         0      0      0       0      0  
1      0      0     0         0      0      0       0      0  
2      0      0     0         0      0      0       0      0  
3      0      0     0         0      0      0       0      0  
4      0      0     0         0      0      0       0      0  
..   ...    ...   ...       ...    ...    ...     ...    ...  
596    0      0     0         0      0      0       0      0  
597    0      0     0         0      0      0       0      0  
598    0      0     0         0      0      0       0      0  
599    0      0     0         0      0      0       0      0  
600    0      0     0         0      0      0       0      0  

[601 rows x 3408 columns]

In [22]:
df_lw = str([row['Query'] for index,row in df.iterrows() if row['Label'] == 'LW'])

df_lw

'["\' ;", \' #\', "\' -- --", "\' -- #", "\' -- %", "\' -- \'", "\') ;", "\') #", "\') -- --", "\') -- #", "\') -- %", "\') -- \'", "\'] ;", "\'] #", "\'] -- --", "\'] -- #", "\'] -- %", "\'] -- \'", "\' ;", \'" #\', \'" -- --\', \'" -- #\', \' -- %\', \'" -- \\\'\', "-\'", " \'", "&\'", "^\'", "*\'", \'"-"\', \'" "\', \'"&"\', \'"^"\', \'"*"\', "admin\' --", "admin\' #", "admin\'/*", \'admin" --\', \'admin" #\', \'admin"/*\', \'sqlvuln\', \'+sqlvuln\', \'sqlvuln;\', \' ( sqlvuln ) \', "a\'", \'?\', \'<>"\\\'%; )  ( &+\', \'sqlattempt1\', \' ( sqlattempt2 ) \', \'|\', \'%7C\', \'*|\', \'%2A%7C\', \'* ( | ( mail = *  )  )  \', \'%2A%28%7C%28mail%3D%2A%29%29\', \'* ( | ( objectclass = *  )  )  \', \'%2A%28%7C%28objectclass%3D%2A%29%29\', \' ( \', 0.28, \' ) \', 0.29, \'&\', 0.26, \'!\', 0.21, \'/\', \'//\', \'//*\', \'*/*\', \'*|\', \' --\', \'&\', \'//\', \'|\', "a\'", \'*/*\', \' ( \', \'/\', \' ) \', \'//*\', \'!\', \'&1c\', "a\' --", \' -- \', "1\\\\\'1", "1\'1", "\\\\\'; desc users;

In [23]:
vec5= CountVectorizer()


In [25]:
arr5=vec5.fit_transform(input.df_lw)
table_LW=pd.DataFrame(arr5.toarray(), columns=vec2.get_feature_names())

AttributeError: 'function' object has no attribute 'df_lw'