In [3]:
import pandas as pd
import numpy as np

In [4]:
df= pd.read_excel(r'sqli.xlsx', engine='openpyxl')
df

Query Label  Unnamed: 2  \
0      )  union select * from information_schema.tab...    MD         NaN   
1     1 union all select 1,2,3,4,5,6,name from sysob...    MD         NaN   
2                          union all select @@version--    MD         NaN   
3      union select * from users where login  =  cha...    MD         NaN   
4                                          union select    MD         NaN   
...                                                 ...   ...         ...   
1994   Their motto , large billboard stated &quot; W...    NV         NaN   
1995   In wanted point danger even bigger ruins Schw...    NV         NaN   
1996   Chatting many people passing &quot; construct...    NV         NaN   
1997   However , beginning resign town continues sta...    NV         NaN   
1998   We told public statements made Mayor also imp...    NV         NaN   

      Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6  Unnamed: 7  
0            NaN         NaN         NaN         NaN         NaN  
1            NaN         NaN         NaN         NaN         NaN  
2            NaN         NaN         NaN         NaN         NaN  
3            NaN         NaN         NaN         NaN         NaN  
4            NaN         NaN         NaN         NaN         NaN  
...          ...         ...         ...         ...         ...  
1994         NaN         NaN         NaN         NaN         NaN  
1995         NaN         NaN         NaN         NaN         NaN  
1996         NaN         NaN         NaN         NaN         NaN  
1997         NaN         NaN         NaN         NaN         NaN  
1998         NaN         NaN         NaN         NaN         NaN  

[1999 rows x 8 columns]

In [9]:
 from sklearn.feature_extraction.text import CountVectorizer
df_MD = [row['Query'] for index,row in df.iterrows() if row['Label'] == 'MD']
df_MD


[' )  union select * from information_schema.tables;',
 "1 union all select 1,2,3,4,5,6,name from sysobjects where xtype  =  'u' --",
 ' union all select @@version--',
 ' union select * from users where login  =  char ( 114,111,111,116 ) ;',
 ' union select',
 " union select 1,load_file ( '/etc/passwd' ) ,1,1,1;",
 ' union  ( select @@version )  --',
 ' union  ( select NULL,  ( select @@version  )  )   --',
 ' union  ( select NULL, NULL,  ( select @@version  )  )   --',
 ' union  ( select NULL, NULL, NULL,   ( select @@version  )  )   --',
 ' union  ( select NULL, NULL, NULL, NULL,   ( select @@version  )  )   --',
 ' union  ( select NULL, NULL, NULL, NULL,  NULL,  ( select @@version  )  )   --',
 ' 1 + ( \\ )  union select null,@@VERSION -- 1',
 ' 1.&&1 union select 1,version (  )  -- 1',
 ' 1.&&@ union select 1,version (  )  -- 1',
 ' 1 +  ( \\. )  union select null,@@VERSION -- 1',
 ' 1.  union select 1,version (  )  -- 1',
 ' 1. union select 1,banner from v$version where rownum = 1

In [13]:
vec = CountVectorizer()

In [23]:
l=vec.fit_transform(df_MD)
print(l.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]]


In [15]:
 print(vec.get_feature_names())

['11', '111', '114', '116', '1234', '1_', '1a', '81dc9bdb52d04dc20036dbd8313ed055', 'admin', 'all', 'and', 'banner', 'char', 'datadir', 'etc', 'from', 'information_schema', 'load_file', 'login', 'name', 'null', 'passwd', 'rownum', 'select', 'sysobjects', 'tables', 'union', 'users', 'version', 'where', 'x27union', 'xtype']


In [20]:
# print(l.toarray())
table_MD=pd.DataFrame(l.toarray(), columns=vec.get_feature_names())
table_MD

11  111  114  116  1234  1_  1a  81dc9bdb52d04dc20036dbd8313ed055  admin  \
0     0    0    0    0     0   0   0                                 0      0   
1     0    0    0    0     0   0   0                                 0      0   
2     0    0    0    0     0   0   0                                 0      0   
3     0    2    1    1     0   0   0                                 0      0   
4     0    0    0    0     0   0   0                                 0      0   
..   ..  ...  ...  ...   ...  ..  ..                               ...    ...   
450   0    0    0    0     0   0   0                                 0      0   
451   0    0    0    0     0   0   0                                 0      0   
452   0    0    0    0     0   0   0                                 0      0   
453   0    0    0    0     0   0   0                                 0      0   
454   0    0    0    0     0   0   0                                 0      0   

     all  ...  rownum  select  sysobjects  tables  union  users  version  \
0      0  ...       0       1           0       1      1      0        0   
1      1  ...       0       1           1       0      1      0        0   
2      1  ...       0       1           0       0      1      0        1   
3      0  ...       0       1           0       0      1      1        0   
4      0  ...       0       1           0       0      1      0        0   
..   ...  ...     ...     ...         ...     ...    ...    ...      ...   
450    0  ...       0       1           0       0      1      0        0   
451    0  ...       0       1           0       0      1      0        0   
452    0  ...       0       1           0       0      1      0        0   
453    0  ...       0       1           0       0      1      0        0   
454    1  ...       0       1           1       0      1      0        0   

     where  x27union  xtype  
0        0         0      0  
1        1         0      1  
2        0         0      0  
3        1         0      0  
4        0         0      0  
..     ...       ...    ...  
450      0         0      0  
451      0         0      0  
452      0         0      0  
453      0         0      0  
454      1         0      1  

[455 rows x 32 columns]